packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@swc/core': true
  cbor-extract: true
  esbuild: true
  nx: true
  puppeteer: true
  unrs-resolver: true

catalog:
  '@types/qrcode': ^1.5.6
  jose: ^6.2.3
  qrcode: ^1.5.4
  typescript: ^5.9.3
  vitest: ~4.1.10
  zod: ^4.3.6

catalogs:
  node:
    '@types/node': ^22.19.9
    pino: ^10.0.0
    pino-pretty: ^13.1.1

  fastify:
    '@fastify/autoload': ^6.3.1
    '@fastify/cookie': ^11.0.2
    '@fastify/cors': ^11.2.0
    '@fastify/env': ^6.0.0
    '@fastify/formbody': ^8.0.2
    '@fastify/helmet': ^13.0.2
    '@fastify/sensible': ^6.0.3
    '@fastify/static': ^10.1.0
    '@fastify/swagger': ^9.5.2
    '@fastify/swagger-ui': ^5.2.3
    fastify: ^5.8.5
    fastify-plugin: ^5.0.1

  pagopa:
    '@pagopa/io-wallet-oauth2': 1.5.4-alpha-20260717125503
    '@pagopa/io-wallet-oid-federation': 1.5.4-alpha-20260717125503
    '@pagopa/io-wallet-oid4vci': 1.5.4-alpha-20260717125503
    '@pagopa/io-wallet-oid4vp': 1.5.4-alpha-20260717125503
    '@pagopa/io-wallet-utils': 1.5.4-alpha-20260717125503

cleanupUnusedCatalogs: true
linkWorkspacePackages: true
packageImportMethod: 'clone-or-copy'
