import type { ProtocolObservedScenarioDefinition } from '../definitions.js';

export const wp017Scenario: ProtocolObservedScenarioDefinition = {
  id: 'WP_017',
  title: 'Negative Path: Wallet Instance rejects a Trust Anchor key not matching the out-of-band key',
  phase: 'ISSUANCE',
  automationMode: 'interactive-protocol-observed',
  services: ['credentialIssuer', 'federation'],
  stimulus: {
    type: 'credential-offer',
    delivery: ['deep-link', 'qr']
  },
  setup: {
    trustAnchorFault: { type: 'entity-configuration-nonmatching-signing-key' }
  },
  entryEvent: 'trust_anchor.entity_configuration.requested',
  requiredEvents: [
    {
      event: 'trust_anchor.entity_configuration.requested',
      service: 'federation',
      correlation: 'allow-uncorrelated-post-start',
      match: { endpoint: '/.well-known/openid-federation' }
    },
    {
      event: 'trust_anchor.fault.applied',
      service: 'federation',
      correlation: 'allow-uncorrelated-post-start',
      match: {
        endpoint: '/.well-known/openid-federation',
        faultProfileType: 'entity-configuration-nonmatching-signing-key'
      }
    }
  ],
  forbiddenEvents: ['issuer.par.requested'],
  timeouts: {
    testerActionMs: 60_000,
    protocolStepMs: 60_000,
    forbiddenObservationMs: 30_000,
    vitestTestMs: 120_000
  },
  verdictRules: [
    { type: 'entry-event-required' },
    { type: 'required-events-in-order' },
    { type: 'no-forbidden-events-after-entry' }
  ],
  instructions: {
    goal: 'Verify that the Wallet Instance rejects a Trust Anchor Entity Configuration whose published key does not match the Trust Anchor key distributed out-of-band.',
    expectedBehavior:
      'After opening the credential offer, the wallet must resolve the Trust Anchor Entity Configuration, verify that its self-consistent signing key does not match the configured out-of-band Trust Anchor key, log the discrepancy according to its own policy without exposing cryptographic secrets, and terminate the issuance flow without continuing to the Credential Issuer PAR endpoint. The harness observes the network behavior and fault evidence; it does not automatically verify wallet-internal logging.',
    prerequisites: [
      'The wallet app under test is installed and can open credential offer deep links or scan credential offer QR payloads.',
      'Run the test from the workspace root, where config.ini and the compiled local services are available.',
      'The Wallet Instance is configured out-of-band with the nominal Trust Anchor public federation key generated by itwct init.',
      'The device running the wallet can reach the local Credential Issuer and Trust Anchor URLs printed by this test.'
    ],
    steps: [
      'Start this scenario with itwct test issuance. The CLI starts the required Trust Anchor and Credential Issuer services, activates the nonmatching signing-key fault on the Trust Anchor, and waits for their readiness.',
      'Open the printed credential offer deep link or scan the QR payload with the Wallet Instance.',
      'Keep the wallet and test process running while the wallet resolves the trust chain and inspects the Trust Anchor Entity Configuration.',
      'Do not continue any consent or identity verification step: the expected outcome is that the wallet stops after rejecting the nonmatching Trust Anchor key.',
      'The runner will continue automatically after the wallet requests the Trust Anchor Entity Configuration and the fault application is recorded, or once the negative-observation window elapses without the wallet continuing to PAR.'
    ]
  },
  missingRequiredEventPolicy: 'inconclusive'
};
