import * as fs from 'node:fs';
import { request as httpRequest } from 'node:http';
import { request as httpsRequest } from 'node:https';
import { join } from 'node:path';

import { beforeAll, describe, expect, it } from 'vitest';

function resolveRpBaseUrl(): string {
  const fromEnv = process.env.ITW_CT_RP_BASE_URL?.trim();
  if (fromEnv) {
    let normalized = fromEnv;
    while (normalized.endsWith('/')) {
      normalized = normalized.slice(0, -1);
    }
    return normalized;
  }

  const port = process.env.ITW_CT_RP_PORT?.trim() || '8080';
  const httpsRaw = process.env.ITW_CT_HTTPS?.trim().toLowerCase();
  const httpsEnabled = httpsRaw !== undefined ? httpsRaw === 'true' || httpsRaw === '1' : true;
  const protocol = httpsEnabled ? 'https' : 'http';
  return `${protocol}://127.0.0.1:${port}`;
}

function decodeJwtPayload<T>(jwt: string): T {
  const parts = jwt.split('.');
  if (parts.length !== 3) {
    throw new Error('Invalid JWT format');
  }

  const payload = Buffer.from(parts[1]!, 'base64url').toString('utf8');
  return JSON.parse(payload) as T;
}

function resolveTransportBaseUrl(baseUrl: string): string {
  const url = new URL(baseUrl);
  // TLS cert generated by local init commonly uses localhost SAN only.
  // Keep logical RP base URL untouched, but route transport to localhost to satisfy cert validation.
  if (url.protocol === 'https:' && url.hostname === '127.0.0.1') {
    url.hostname = 'localhost';
  }
  return url.toString().replace(/\/$/, '');
}

function requireSearchParam(url: URL, name: string): string {
  const value = url.searchParams.get(name);
  if (!value) {
    throw new Error(`Missing ${name} query parameter`);
  }
  return value;
}

type HttpResponse = {
  status: number;
  headers: Record<string, string | string[] | undefined>;
  body: string;
};

async function requestWithOptionalCa(input: {
  url: string;
  method?: 'GET' | 'POST';
  headers?: Record<string, string>;
  body?: string;
  caCertPem?: string;
}): Promise<HttpResponse> {
  const target = new URL(input.url);
  const isHttps = target.protocol === 'https:';
  const requestImpl = isHttps ? httpsRequest : httpRequest;

  return await new Promise<HttpResponse>((resolve, reject) => {
    const req = requestImpl(
      target,
      {
        method: input.method ?? 'GET',
        headers: input.headers,
        ...(isHttps
          ? {
              ca: input.caCertPem,
              rejectUnauthorized: true
            }
          : {})
      },
      (res) => {
        const chunks: Buffer[] = [];
        res.on('data', (chunk) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));
        res.on('end', () => {
          resolve({
            status: res.statusCode ?? 0,
            headers: res.headers as Record<string, string | string[] | undefined>,
            body: Buffer.concat(chunks).toString('utf8')
          });
        });
      }
    );

    req.on('error', reject);
    if (input.body !== undefined) {
      req.write(input.body);
    }
    req.end();
  });
}

function getHeaderValue(headers: Record<string, string | string[] | undefined>, name: string): string | undefined {
  const value = headers[name.toLowerCase()];
  return Array.isArray(value) ? value.join(',') : value;
}

type RequestObjectResponse = {
  url: string;
};

describe('RP attribute deletion conformance matrix', () => {
  const rpBaseUrl = resolveRpBaseUrl();
  const transportBaseUrl = resolveTransportBaseUrl(rpBaseUrl);
  let caCertPem: string | undefined;

  beforeAll(() => {
    // Derive certificate path from data dir only.
    const dataDir = process.env.ITW_CT_DATA_DIR?.trim();
    if (!dataDir) {
      throw new Error('Missing required env: ITW_CT_DATA_DIR');
    }

    const caCertPath = join(dataDir, 'tls-cert.pem');

    if (rpBaseUrl.startsWith('https://') && !fs.existsSync(caCertPath)) {
      throw new Error(`TLS certificate not found in data dir: ${caCertPath}`);
    }

    if (rpBaseUrl.startsWith('https://')) {
      caCertPem = fs.readFileSync(caCertPath, 'utf8');
    }
  });

  it('WP_116: federation metadata exposes a valid RP erasure endpoint', async () => {
    const response = await requestWithOptionalCa({
      url: `${transportBaseUrl}/.well-known/openid-federation`,
      caCertPem
    });
    const body = response.body;

    expect(response.status).toBe(200);
    expect(getHeaderValue(response.headers, 'content-type')).toContain('application/entity-statement+jwt');

    const metadataJwt = body;
    const payload = decodeJwtPayload<Record<string, unknown>>(metadataJwt);
    const metadata = payload['metadata'] as Record<string, unknown> | undefined;
    const verifier = metadata?.['openid_credential_verifier'] as Record<string, unknown> | undefined;
    const erasureEndpoint = verifier?.['erasure_endpoint'];

    expect(typeof erasureEndpoint).toBe('string');
    const erasureUrl = new URL(String(erasureEndpoint));
    expect(erasureUrl.pathname).toBe('/auth/erasure');

    if (process.env.ITW_CT_RP_BASE_URL?.trim()) {
      const configuredBaseUrl = new URL(rpBaseUrl);
      expect(erasureUrl.origin).toBe(configuredBaseUrl.origin);
    }
  });

  it('WP_117: wallet sends a valid deletion request to RP erasure endpoint', async () => {
    const requestObjectResponse = await requestWithOptionalCa({
      url: `${transportBaseUrl}/request-object`,
      method: 'POST',
      headers: {
        'content-type': 'application/json'
      },
      body: JSON.stringify({
        dcqlQuery: {
          credentials: [{ id: 'pid', format: 'dc+sd-jwt' }]
        },
        flow_type: 'cross-device'
      }),
      caCertPem
    });

    const requestObjectBody = JSON.parse(requestObjectResponse.body) as RequestObjectResponse;
    expect(requestObjectResponse.status).toBe(200);

    const state = requireSearchParam(new URL(requestObjectBody.url), 'state');
    const callbackUrl = 'https://wallet.example.org/erasure-callback';

    const erasureResponse = await requestWithOptionalCa({
      url: `${transportBaseUrl}/auth/erasure?state=${encodeURIComponent(state)}&callback_url=${encodeURIComponent(callbackUrl)}&attributes=family_name,given_name&attributes=birth_date`,
      caCertPem
    });

    const erasureBody = erasureResponse.body;
    expect(erasureResponse.status, erasureBody).toBe(204);
    expect(erasureBody).toBe('');
  });

  it('WP_117: RP rejects deletion request with invalid state', async () => {
    const callbackUrl = 'https://wallet.example.org/erasure-callback';
    const erasureResponse = await requestWithOptionalCa({
      url: `${transportBaseUrl}/auth/erasure?state=${encodeURIComponent('not-a-valid-uuid')}&callback_url=${encodeURIComponent(callbackUrl)}`,
      caCertPem
    });

    const erasureBody = JSON.parse(erasureResponse.body) as {
      error: string;
      error_description: string;
    };

    expect(erasureResponse.status).toBe(400);
    expect(erasureBody.error).toBe('bad_request');
    expect(erasureBody.error_description.length).toBeGreaterThan(0);
  });

  it('WP_118: wallet receives successful callback outcome after RP erasure redirect flow', async () => {
    const requestObjectResponse = await requestWithOptionalCa({
      url: `${transportBaseUrl}/request-object`,
      method: 'POST',
      headers: {
        'content-type': 'application/json'
      },
      body: JSON.stringify({
        dcqlQuery: {
          credentials: [{ id: 'pid', format: 'dc+sd-jwt' }]
        },
        flow_type: 'cross-device'
      }),
      caCertPem
    });

    const requestObjectBody = JSON.parse(requestObjectResponse.body) as RequestObjectResponse;
    expect(requestObjectResponse.status).toBe(200);

    const state = requireSearchParam(new URL(requestObjectBody.url), 'state');
    const callbackUrl = 'https://wallet.example.org/after-erasure';

    const erasureResponse = await requestWithOptionalCa({
      url: `${transportBaseUrl}/auth/erasure?state=${encodeURIComponent(state)}&callback_url=${encodeURIComponent(callbackUrl)}`,
      caCertPem
    });
    expect(erasureResponse.status).toBe(204);

    const statusResponse = await requestWithOptionalCa({
      url: `${transportBaseUrl}/status/${encodeURIComponent(state)}`,
      caCertPem
    });
    const statusBody = JSON.parse(statusResponse.body) as { redirect_uri: string };

    expect(statusResponse.status).toBe(200);
    expect(statusBody.redirect_uri).toBe(`${callbackUrl}?response_code=success`);
  });
});
