import { webcrypto } from 'node:crypto';
import { isIP } from 'node:net';

import {
  AuthorityKeyIdentifierExtension,
  BasicConstraintsExtension,
  Extension,
  KeyUsageFlags,
  KeyUsagesExtension,
  SubjectAlternativeNameExtension,
  SubjectKeyIdentifierExtension,
  X509Certificate,
  X509CertificateGenerator
} from '@peculiar/x509';

type SelfSignedCertificateFromJwkOptions = {
  commonName?: string;
  /**
   * Marks the certificate as a CA and gives it the key usages a CA needs. Only
   * the Trust Anchor federation certificate sets it: it is the root every
   * federation `x5c` chain terminates at, so it has to be allowed to sign the
   * subordinate CA certificates below it.
   */
  isCertificateAuthority?: boolean;
  /**
   * Key usages asserted for the subject key. Defaults to `digitalSignature`,
   * which is what a signing certificate needs; an encryption certificate
   * overrides it with `keyAgreement`. Ignored when `isCertificateAuthority` is
   * set, since a CA's usages are fixed.
   */
  keyUsageFlags?: number;
  organizationalUnitName?: string;
  organizationName?: string;
};

/**
 * Validity of every CA certificate in the local federation: the Trust Anchor
 * federation certificate and the subordinate CA certificates it signs. Leaf
 * certificates get one year.
 */
const CA_CERTIFICATE_VALIDITY_YEARS = 5;

type Jwk = Record<string, unknown>;
type Jwks = { keys: Jwk[] };

type IssuerChainCertificateOptions = {
  commonName?: string;
  organizationName?: string;
};

type IssuerCertificateOptions = {
  altNames?: string[];
  commonName?: string;
  organizationName?: string;
};

function stripPrivateKeyMaterial(jwk: Record<string, unknown>): Record<string, unknown> {
  const {
    d: _d,
    key_ops: _keyOps,
    ...publicJwk
  } = jwk as Record<string, unknown> & {
    d?: string;
    key_ops?: string[];
  };
  void _d;
  void _keyOps;
  return publicJwk;
}

/** Imports an EC P-256 private JWK as a Web Crypto ECDSA private/public key pair.
 *
 * `use`, `alg` and `key_ops` are dropped first. Web Crypto validates all three
 * against the algorithm the import asks for, so a key declaring `ECDH-ES` /
 * `use: 'enc'` / `deriveBits` would be refused outright — and the encryption key
 * has to be importable here to be certified at all, since issuing its
 * certificate means producing a signature over it. The stripped members say what
 * the key is *for*; the P-256 key pair underneath is the same either way.
 *
 * @param jwk - The private EC JWK to import.
 * @returns The imported private and public `CryptoKey`s.
 */
async function importEcKeyPairFromJwk(
  jwk: Jwk
): Promise<{ privateKey: webcrypto.CryptoKey; publicKey: webcrypto.CryptoKey }> {
  const { alg: _alg, use: _use, key_ops: _keyOps, ...privateJwk } = jwk;
  void _alg;
  void _use;
  void _keyOps;
  const publicJwk = stripPrivateKeyMaterial(privateJwk);

  const publicKey = await webcrypto.subtle.importKey('jwk', publicJwk, { name: 'ECDSA', namedCurve: 'P-256' }, true, [
    'verify'
  ]);
  const privateKey = await webcrypto.subtle.importKey('jwk', privateJwk, { name: 'ECDSA', namedCurve: 'P-256' }, true, [
    'sign'
  ]);

  return { privateKey, publicKey };
}

/** Selects a private ES256 signing key (`kty=EC`, `alg=ES256`, `use=sig`)
 * from a JWKS, optionally by key ID.
 *
 * The issuer and Relying Party JWKS both also contain an ECDH-ES encryption
 * key, so certificate generation must select the key that actually signs.
 * Neither holds a second signing key: the Relying Party's federation key lives
 * in its own `rp/federation-key.jwk.json`, which is what keeps the two roles
 * distinguishable by something other than position.
 *
 * @param jwks - The JWKS to search.
 * @param kid - The optional key ID to select.
 * @returns The private ES256 signing JWK.
 */
export function selectEs256SigningJwk(jwks: Jwks, kid?: string): Jwk {
  const candidates = jwks.keys.filter(
    (key) =>
      key.kty === 'EC' &&
      key.alg === 'ES256' &&
      key.use === 'sig' &&
      typeof key.d === 'string' &&
      (kid === undefined || key.kid === kid)
  );

  if (candidates.length === 0) {
    throw new Error(
      `No private ES256 signing key (kty=EC, alg=ES256, use=sig) found${kid ? ` with kid "${kid}"` : ''} in JWKS`
    );
  }
  if (candidates.length > 1) {
    throw new Error(
      `Multiple private ES256 signing keys found${kid ? ` with kid "${kid}"` : ''} in JWKS; expected exactly one`
    );
  }

  return candidates[0];
}

/** Selects the private ECDH-ES encryption key (`kty=EC`, `alg=ECDH-ES`,
 * `use=enc`) from a JWKS.
 *
 * Both the issuer and the Relying Party keep exactly one, so more than one
 * candidate means the JWKS was generated by something other than `init` and the
 * certificate about to be issued would bind an arbitrary key.
 *
 * @param jwks - The JWKS to search.
 * @returns The private ECDH-ES encryption JWK.
 */
export function selectEcdhEsEncryptionJwk(jwks: Jwks): Jwk {
  const candidates = jwks.keys.filter(
    (key) => key.kty === 'EC' && key.alg === 'ECDH-ES' && key.use === 'enc' && typeof key.d === 'string'
  );

  if (candidates.length === 0) {
    throw new Error('No private ECDH-ES encryption key (kty=EC, alg=ECDH-ES, use=enc) found in JWKS');
  }
  if (candidates.length > 1) {
    throw new Error('Multiple private ECDH-ES encryption keys found in JWKS; expected exactly one');
  }

  return candidates[0];
}

export async function createSelfSignedCertificateFromJwk(
  jwk: Record<string, unknown>,
  {
    commonName = 'Issuer Signing Certificate',
    isCertificateAuthority = false,
    keyUsageFlags = KeyUsageFlags.digitalSignature,
    organizationalUnitName,
    organizationName = 'ITW Conformance Tool'
  }: SelfSignedCertificateFromJwkOptions = {}
): Promise<string> {
  const { privateKey, publicKey } = await importEcKeyPairFromJwk(jwk);

  const now = new Date();
  const notAfter = new Date(now);
  // A CA must outlive everything beneath it: the subordinate CA certificates it
  // signs are given five years, so a one-year root would expire first and
  // invalidate chains that are otherwise still current.
  notAfter.setFullYear(notAfter.getFullYear() + (isCertificateAuthority ? CA_CERTIFICATE_VALIDITY_YEARS : 1));

  const extensions: Extension[] = [
    new BasicConstraintsExtension(isCertificateAuthority, isCertificateAuthority ? 1 : undefined, true),
    new KeyUsagesExtension(
      isCertificateAuthority
        ? KeyUsageFlags.digitalSignature | KeyUsageFlags.keyCertSign | KeyUsageFlags.cRLSign
        : keyUsageFlags,
      true
    ),
    await SubjectKeyIdentifierExtension.create(publicKey)
  ];

  const organizationalUnit = organizationalUnitName ? `, OU=${organizationalUnitName}` : '';
  const certificate = await X509CertificateGenerator.createSelfSigned({
    keys: { privateKey, publicKey },
    name: `C=IT, O=${organizationName}${organizationalUnit}, CN=${commonName}`,
    notBefore: now,
    notAfter,
    signingAlgorithm: { name: 'ECDSA', hash: 'SHA-256' },
    extensions
  });

  return certificate.toString();
}

/** Generates the Trust Anchor federation certificate from its existing signing JWK.
 *
 * This is the root of every federation `x5c` chain the local services publish —
 * the Relying Party, Credential Issuer and Wallet Provider all chain up to it —
 * so it is issued as a CA certificate.  
 *
 * No `extendedKeyUsage` is asserted: an EKU on a CA constrains every
 * certificate beneath it, and the previous `serverAuth`/`clientAuth` pair would
 * have excluded the federation signing leaves it now issues. TLS is served from
 * the separate local root CA under `<data_dir>/tls`.
 */
export async function createTrustAnchorCertificateFromJwk(
  jwk: Record<string, unknown>,
  commonName: string
): Promise<string> {
  return createSelfSignedCertificateFromJwk(jwk, {
    commonName,
    isCertificateAuthority: true,
    organizationalUnitName: 'Trust Anchor'
  });
}

/** Creates the issuer intermediate CA certificate (`issuer/intermediate-cert.pem`).
 *
 * Its subject public key comes from the intermediate CA JWK, while its
 * issuer DN and signature come from the trust-anchor federation key and
 * certificate, chaining it to `trust-anchor/federation-cert.pem`.
 *
 * @param intermediateJwk - The intermediate CA's private ES256 JWK; its public key becomes the certificate's subject key.
 * @param trustAnchorJwk - The trust-anchor federation private ES256 JWK, used to sign the certificate.
 * @param trustAnchorCertificatePem - The trust-anchor federation certificate, used for the issuer DN.
 * @param options - Optional subject overrides.
 * @returns A PEM-encoded intermediate CA certificate.
 */
export async function createIntermediateCertificateFromJwk(
  intermediateJwk: Jwk,
  trustAnchorJwk: Jwk,
  trustAnchorCertificatePem: string,
  {
    commonName = 'Issuer Intermediate CA',
    organizationName = 'ITW Conformance Tool'
  }: IssuerChainCertificateOptions = {}
): Promise<string> {
  const { publicKey: intermediatePublicKey } = await importEcKeyPairFromJwk(intermediateJwk);
  const { privateKey: trustAnchorPrivateKey, publicKey: trustAnchorPublicKey } =
    await importEcKeyPairFromJwk(trustAnchorJwk);

  const trustAnchorCertificate = new X509Certificate(trustAnchorCertificatePem);

  const now = new Date();
  const notAfter = new Date(now);
  notAfter.setFullYear(notAfter.getFullYear() + CA_CERTIFICATE_VALIDITY_YEARS);

  const certificate = await X509CertificateGenerator.create({
    issuer: trustAnchorCertificate.subject,
    subject: `C=IT, O=${organizationName}, CN=${commonName}`,
    notBefore: now,
    notAfter,
    publicKey: intermediatePublicKey,
    signingKey: trustAnchorPrivateKey,
    signingAlgorithm: { name: 'ECDSA', hash: 'SHA-256' },
    extensions: [
      new BasicConstraintsExtension(true, 0, true),
      new KeyUsagesExtension(KeyUsageFlags.keyCertSign | KeyUsageFlags.cRLSign, true),
      await SubjectKeyIdentifierExtension.create(intermediatePublicKey),
      await AuthorityKeyIdentifierExtension.create(trustAnchorPublicKey)
    ]
  });

  return certificate.toString();
}

/** Creates a leaf certificate signed by an intermediate CA.
 *
 * Its subject public key comes from the runtime ES256 signing key, while its
 * issuer DN and signature come from the intermediate CA key/certificate.
 *
 * @param signingJwk - The entity's private ES256 signing JWK; its public key becomes the certificate's subject key.
 * @param intermediateJwk - The intermediate CA's private ES256 JWK, used to sign the certificate.
 * @param intermediateCertificatePem - The intermediate CA certificate, used for the issuer DN.
 * @param entityUrl - The configured entity URL, used to derive the subject CN and SAN.
 * @param options - Optional subject overrides.
 * @returns A PEM-encoded leaf certificate.
 */
export async function createLeafCertificateFromJwk(
  signingJwk: Jwk,
  intermediateJwk: Jwk,
  intermediateCertificatePem: string,
  entityUrl: string,
  { altNames = [], commonName, organizationName = 'ITW Conformance Tool' }: IssuerCertificateOptions = {}
): Promise<string> {
  const { publicKey: entityPublicKey } = await importEcKeyPairFromJwk(signingJwk);
  const { privateKey: intermediatePrivateKey, publicKey: intermediatePublicKey } =
    await importEcKeyPairFromJwk(intermediateJwk);

  const intermediateCertificate = new X509Certificate(intermediateCertificatePem);
  const subjectCommonName = commonName ?? new URL(entityUrl).hostname;
  const uniqueAltNames = [...new Set([new URL(entityUrl).hostname, ...altNames])];

  const now = new Date();
  const notAfter = new Date(now);
  notAfter.setFullYear(notAfter.getFullYear() + 1);

  const certificate = await X509CertificateGenerator.create({
    issuer: intermediateCertificate.subject,
    subject: `C=IT, O=${organizationName}, CN=${subjectCommonName}`,
    notBefore: now,
    notAfter,
    publicKey: entityPublicKey,
    signingKey: intermediatePrivateKey,
    signingAlgorithm: { name: 'ECDSA', hash: 'SHA-256' },
    extensions: [
      new BasicConstraintsExtension(false, undefined, true),
      new KeyUsagesExtension(KeyUsageFlags.digitalSignature, true),
      new SubjectAlternativeNameExtension(
        uniqueAltNames.map((name) => ({ type: isIP(name) ? 'ip' : 'dns', value: name }))
      ),
      await SubjectKeyIdentifierExtension.create(entityPublicKey),
      await AuthorityKeyIdentifierExtension.create(intermediatePublicKey)
    ]
  });

  return certificate.toString();
}

/** Creates the issuer leaf certificate (`issuer/cert.pem`).
 *
 * Its subject public key comes from the ES256 signing key in
 * `issuer/jwks.json`, while its issuer DN and signature come from the
 * intermediate CA key/certificate, chaining it through
 * `issuer/intermediate-cert.pem`.
 *
 * @param issuerSigningJwk - The issuer's private ES256 signing JWK; its public key becomes the certificate's subject key.
 * @param intermediateJwk - The intermediate CA's private ES256 JWK, used to sign the certificate.
 * @param intermediateCertificatePem - The intermediate CA certificate, used for the issuer DN.
 * @param credentialIssuerUrl - The configured credential-issuer URL, used to derive the subject CN and SAN.
 * @param options - Optional subject overrides.
 * @returns A PEM-encoded issuer leaf certificate.
 */
export async function createIssuerCertificateFromJwk(
  issuerSigningJwk: Jwk,
  intermediateJwk: Jwk,
  intermediateCertificatePem: string,
  credentialIssuerUrl: string,
  options: IssuerCertificateOptions = {}
): Promise<string> {
  return createLeafCertificateFromJwk(
    issuerSigningJwk,
    intermediateJwk,
    intermediateCertificatePem,
    credentialIssuerUrl,
    options
  );
}

/** Creates the Relying Party intermediate CA certificate (`rp/intermediate-cert.pem`).
 *
 * Chains the Relying Party's federation key to the Trust Anchor the same way
 * the issuer and the Wallet Provider are chained, so all three leaf entities
 * present the same `x5c` shape — `[leaf, intermediate]`, with the Trust Anchor
 * root left out because a verifier is expected to hold it already.
 *
 * @param intermediateJwk - The Relying Party intermediate CA's private ES256 JWK; its public key becomes the certificate's subject key.
 * @param trustAnchorJwk - The trust-anchor federation private ES256 JWK, used to sign the certificate.
 * @param trustAnchorCertificatePem - The trust-anchor federation certificate, used for the issuer DN.
 * @returns A PEM-encoded intermediate CA certificate.
 */
export async function createRelyingPartyIntermediateCertificateFromJwk(
  intermediateJwk: Jwk,
  trustAnchorJwk: Jwk,
  trustAnchorCertificatePem: string
): Promise<string> {
  return createIntermediateCertificateFromJwk(intermediateJwk, trustAnchorJwk, trustAnchorCertificatePem, {
    commonName: 'Relying Party Intermediate CA'
  });
}

/** Creates the Relying Party federation leaf certificate (`rp/federation-cert.pem`).
 *
 * Its subject public key is the federation key that signs the Relying Party
 * Entity Configuration and its Trust Mark — never the authorization-request
 * signing key, which is certified separately and self-signed.
 *
 * @param federationJwk - The Relying Party's private ES256 federation JWK; its public key becomes the certificate's subject key.
 * @param intermediateJwk - The Relying Party intermediate CA's private ES256 JWK, used to sign the certificate.
 * @param intermediateCertificatePem - The intermediate CA certificate, used for the issuer DN.
 * @param relyingPartyUrl - The configured Relying Party URL, used to derive the subject CN and SAN.
 * @returns A PEM-encoded federation leaf certificate.
 */
export async function createRelyingPartyFederationCertificateFromJwk(
  federationJwk: Jwk,
  intermediateJwk: Jwk,
  intermediateCertificatePem: string,
  relyingPartyUrl: string
): Promise<string> {
  return createLeafCertificateFromJwk(federationJwk, intermediateJwk, intermediateCertificatePem, relyingPartyUrl);
}

/** Creates the self-signed certificate for an ECDH-ES key agreement key.
 *
 * Self-signed, like the signing key's own certificate and unlike the federation
 * key's: the application keys are deliberately certified outside the federation,
 * so neither chains to the Trust Anchor.
 *
 * The certificate asserts `keyAgreement` — what the key is actually for — and
 * `digitalSignature`, without which the self-signature it carries would
 * contradict its own key usage. Producing that signature is the one time this
 * key is used to sign anything: an ECDH-ES key performs key agreement, not
 * signing, and a self-signed certificate is by definition signed by the subject's
 * own key. Certifying it from the sibling signing key instead would avoid that,
 * but the result is not a certificate any path validation accepts — the signing
 * certificate is a leaf, not a CA, so the pair would form no valid chain.
 *
 * @param encryptionJwk - The private ECDH-ES JWK to certify.
 * @param options - Subject overrides.
 * @returns A PEM-encoded self-signed encryption certificate.
 */
export async function createSelfSignedEncryptionCertificateFromJwk(
  encryptionJwk: Jwk,
  options: Omit<SelfSignedCertificateFromJwkOptions, 'isCertificateAuthority' | 'keyUsageFlags'> = {}
): Promise<string> {
  return createSelfSignedCertificateFromJwk(encryptionJwk, {
    ...options,
    keyUsageFlags: KeyUsageFlags.keyAgreement | KeyUsageFlags.digitalSignature
  });
}
