import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

import { importJWK, SignJWT, type JWK } from 'jose';

import type { generateKeyPair } from 'jose';

/** A private signing key as produced by jose's `generateKeyPair`. Named indirectly
 * because `CryptoKey` is not in this package's TypeScript `lib`. */
type SigningKey = Awaited<ReturnType<typeof generateKeyPair>>['privateKey'];

/** Location of the Trust Anchor federation private key inside the shared `data_dir`,
 * as generated by the CLI's `init` command. */
export const TRUST_ANCHOR_FEDERATION_KEY_FILE = join('trust-anchor', 'federation-key.jwk.json');

const DEFAULT_TRUST_MARK_SIGNING_ALG = 'ES256';
const TRUST_MARK_TYP = 'trust-mark+jwt';

/** A Trust Anchor federation private JWK, guaranteed to carry the `kid` that the Trust
 * Anchor advertises in its own Entity Configuration. */
export type TrustAnchorFederationJwk = JWK & { kid: string };

function isEcPrivateJwk(value: unknown): value is JWK {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return false;
  }

  const jwk = value as JWK;
  return (
    jwk.kty === 'EC' &&
    typeof jwk.d === 'string' &&
    typeof jwk.crv === 'string' &&
    typeof jwk.x === 'string' &&
    typeof jwk.y === 'string'
  );
}

/** Reads the Trust Anchor federation private key from the shared `data_dir`.
 *
 * Trust Marks are issued by the Trust Anchor (per OpenID Federation and the IT-Wallet
 * trust model), but each leaf assembles its own Entity Configuration on demand, so the
 * leaf needs the Trust Anchor's signing key to embed a Trust Anchor-issued Trust Mark.
 * In this conformance harness every service runs from one `data_dir` and key material is
 * already shared in the other direction — the Trust Anchor reads each leaf's federation
 * private key to build subordinate statements
 * (apps/itw-trust-anchor/src/plugins/keys.ts) — so reading the Trust Anchor key here
 * keeps the federation self-contained, with no service-to-service call at Entity
 * Configuration build time.
 *
 * @throws {Error} If the file is missing or does not contain an EC private JWK with a `kid`.
 */
export async function loadTrustAnchorFederationJwk(dataDir: string): Promise<TrustAnchorFederationJwk> {
  const keyPath = join(dataDir, TRUST_ANCHOR_FEDERATION_KEY_FILE);
  let content: string;

  try {
    content = await readFile(keyPath, 'utf8');
  } catch {
    throw new Error(
      `Missing required key: ${TRUST_ANCHOR_FEDERATION_KEY_FILE} not found in ${dataDir}. ` +
        `Trust Marks are issued by the Trust Anchor, so its federation key must exist before ` +
        `starting the server (run the CLI's init command).`
    );
  }

  const parsed = JSON.parse(content) as unknown;
  // The CLI has historically written this file both as a JSON object and as a
  // JSON-encoded string; the Trust Anchor's own loader tolerates both, so this must too.
  const jwk = typeof parsed === 'string' ? (JSON.parse(parsed) as unknown) : parsed;

  if (!isEcPrivateJwk(jwk)) {
    throw new Error(
      `Invalid key format in ${TRUST_ANCHOR_FEDERATION_KEY_FILE}: expected an EC private JWK (kty=EC with d/crv/x/y).`
    );
  }

  if (typeof jwk.kid !== 'string' || jwk.kid.length === 0) {
    throw new Error(`Invalid key format in ${TRUST_ANCHOR_FEDERATION_KEY_FILE}: missing a valid "kid".`);
  }

  return jwk as TrustAnchorFederationJwk;
}

export interface CreateTrustMarkOptions {
  /** Entity Identifier of the Trust Mark Issuer — the Trust Anchor. */
  issuerEntityId: string;
  issuedAt: number;
  /** The Trust Mark Issuer's signing key. Its `kid` and `alg` are advertised in the
   * protected header, so it must be resolvable from the issuer's published `jwks`. */
  signingJwk: TrustAnchorFederationJwk;
  /**
   * Signs in place of `signingJwk`, whose `kid` and `alg` the Trust Mark still
   * advertises. Used by fault profiles that need a Trust Mark no federation-published
   * key can verify.
   */
  signingKeyOverride?: SigningKey;
  /** Entity Identifier of the entity the Trust Mark is about. */
  subjectEntityId: string;
  ttlSeconds: number;
  /** The Trust Mark type identifier: a URL in the Trust Mark owner's namespace. Since
   * the Trust Anchor both owns and issues it, no `delegation` claim is required and the
   * Trust Anchor lists itself under `trust_mark_issuers` for this type. */
  trustMarkType: string;
}

/** Builds a Trust Anchor-issued Trust Mark JWT for a leaf entity.
 *
 * The Trust Mark is issued by the Trust Anchor (`iss`) about the leaf (`sub`) and signed
 * with the Trust Anchor's federation key, so a wallet resolves the issuer's keys through
 * the Trust Anchor Entity Configuration it already fetched for the Trust Chain.
 */
export async function createTrustMark(options: CreateTrustMarkOptions): Promise<string> {
  const { issuedAt, issuerEntityId, signingJwk, subjectEntityId, trustMarkType, ttlSeconds } = options;
  const alg = signingJwk.alg ?? DEFAULT_TRUST_MARK_SIGNING_ALG;
  const key = options.signingKeyOverride ?? (await importJWK(signingJwk, alg));

  return new SignJWT({
    ref: `${trustMarkType}/compliance`,
    trust_mark_type: trustMarkType
  })
    .setProtectedHeader({ alg, kid: signingJwk.kid, typ: TRUST_MARK_TYP })
    .setIssuedAt(issuedAt)
    .setIssuer(issuerEntityId)
    .setSubject(subjectEntityId)
    .setExpirationTime(issuedAt + ttlSeconds)
    .sign(key);
}
